<p>All the Cyber Monday prepaid and unlocked phone deals in one place. Updated frequently.</p>
<p>Today, Monday Dec. 2 is Cyber Monday and all the deals should be available now. Many of these end at midnight tonight so don't delay.</p>
<p>Follow me, <a href="https://twitter.com/yeswap">@yeswap on Twitter</a> for the latest updates. <i>Last update 2-Dec-2019.</i></p>
<p><strong><a href="https://www.amazon.com/b/ref=gbps_fcr_m-6_0499_dls_MISD?node=14611812011&amp;gb_f_GB-SUPPLE=dealStates:AVAILABLE%252CWAITLIST%252CWAITLISTFULL%252CUPCOMING,sortOrder:BY_SCORE,enforcedCategories:2335752011&amp;gb_ttl_GB-SUPPLE=Deals%2520on%2520Cell%2520Phones%2520and%2520Accessories&amp;pf_rd_p=ee432437-8875-450e-b18e-32bd8c7a0499&amp;pf_rd_r=AW0BVJZW8BXVHAGF0ZBS&amp;nocache=1575215415256&amp;pf_rd_s=merchandised-search-6&amp;pf_rd_t=101&amp;pf_rd_i=14611812011&amp;pf_rd_m=ATVPDKIKX0DER&amp;ie=UTF8"><span style="font-size: 14pt;">Amazon</span></a> Countdown to Cyber Monday  sale</strong> - Now through Cyber Monday December 2 . Amazon will offer rotating new deals everyday. <strong>Items with links available online now.</strong></p>
<p>TracFone <a href="https://www.amazon.com/TracFone-Rebel-LTE-Prepaid-Smartphone/dp/B07GC5QKTX"><strong>LG Rebel 4 L212VL</strong></a> 16 GB $24.99 (reg $49.99)<br />
Total Wireless <a href="https://www.amazon.com/Wireless-Samsung-Galaxy-Prepaid-Smartphone/dp/B07GC1XCPY"><b>Samsung Galaxy J3 Orbit </b></a>$29.99 (reg 59.99)<br />
Tracfone <strong><a href="https://www.amazon.com/Tracfone-Samsung-Galaxy-Prepaid-Smartphone/dp/B07GBX14NZ?ref_=ast_sto_dp&amp;th=1&amp;psc=1">Samsung Galaxy J3 Orbit</a> S367VL</strong> 16 GB $34.99 (reg $79.99)<br />
Total Wireless <strong><a href="https://www.amazon.com/Wireless-Samsung-Galaxy-Prepaid-Smartphone/dp/B07GC5QFXB">Samsung Galaxy J7 Crown</a> S767VL</strong> $39.99 (reg $89.99)<br />
TracFone <strong><a href="https://www.amazon.com/dp/B07GC5QKVQ">Samsung Galaxy J7 Crown</a></strong> <strong>S767VL</strong> $49.99 (reg $99.99)<br />
Total Wireless <a href="https://www.amazon.com/Total-Wireless-Motorola-Prepaid-Smartphone/dp/B07GBX115M/"><strong>Motorola Moto G6</strong></a> 67.98 (reg $85.15)<br />
Tracfone <strong><a href="https://www.amazon.com/Tracfone-Smartphone-Smartwatch-Bluetooth-SM-R600NZBAXAR/dp/B07S2Z7WY1">Samsung Galaxy S7</a></strong> (new) 32 GB with 1500 Minutes/Text/Data and 1 year of service and Samsung Gear Sport smartwatch (Verizon) $199.99<br />
<br />
Unlocked <a href="https://www.amazon.com/dp/B07N9MF1Q3"><strong>Motorola Moto G7 Play</strong></a> 32 GB $149.99 (reg $199.99)<br />
Unlocked <strong><a href="https://www.amazon.com/Moto-G6-Unlocked-T-Mobile-Warranty/dp/B079Z792J7/ref=sr_1_3?keywords=AT%26T+Prepaid+Motorola+Moto+E5+Play&amp;qid=1574394013&amp;sr=8-3">Motorola Moto G6</a></strong> 32 GB $150.00 (was $249.99)<br />
Unlocked <a href="https://www.amazon.com/Moto-G7-Power-Unlocked-Warranty/dp/B07N9KQDVG"><strong>Motorola Moto G7 Power</strong> </a>64 GB $179.99 (reg $249.99)<br />
Unlocked <a href="https://www.amazon.com/dp/B07N91S9MW"><strong>Motorola Moto G7</strong></a> 64 GB $199.99 (reg $299.99)<br />
Unlocked<strong><b> <a href="https://www.amazon.com/Samsung-Version-Factory-Unlocked-SM-A505UZKNXAA/dp/B07VZL1W7K">Samsung A50 </a></b></strong>64 GB $274.99 (reg $349.99) <br />
Unlocked <a href="https://www.amazon.com/dp/B07R7DY911"><strong>Pixel 3a</strong></a> 64 GB $299.99 (reg $399.99)<strong><br />
</strong>Unlocked <a href="https://www.amazon.com/dp/B07R5CJDD7"><strong>Pixel 3a XL</strong></a> 64 GB $379.99 (reg $479.99)<br />
Unlocked <strong><a href="https://www.amazon.com/gp/product/B07R5B4G5Y">LG G8 ThinQ</a></strong> 128 GB $399.99 (was$849.99)<br />
Unlocked <a href="https://www.amazon.com/Google-Pixel-Just-Black-Unlocked/dp/B07YMNLXL3/"><strong>Pixel 4</strong></a> 64 GB $599.99 (reg $799.99)<br />
Unlocked<a href="https://www.amazon.com/Google-Pixel-Just-Black-Unlocked/dp/B07YMG37J4/?th=1"><strong> Pi</strong><strong>xel 4 XL </strong></a>64 GB $699.99 (reg $899.99)<br />
Unlocked <a href="https://www.amazon.com/Samsung-Galaxy-Factory-Unlocked-Warranty/dp/B07N4M495N"><b>Samsung Galaxy S10e</b></a> 128 GB $549.99 (reg $749.99)<br />
Unlocked <a href="https://www.amazon.com/Samsung-Galaxy-Factory-Unlocked-Warranty/dp/B07YBWNC34"><b>Samsung Galaxy S10</b></a> 128 GB with free AKG headphones $699.99 (reg $899.99)<br />
Unlocked<a href="https://www.amazon.com/Samsung-Factory-Unlocked-Warranty-Headphones/dp/B08224XV8Y"><b> Samsung Galaxy Note 10</b></a> 256 GB $749.99 (reg $949.99)<br />
Unlocked <a href="https://www.amazon.com/Samsung-Galaxy-Factory-Unlocked-Warranty/dp/B07YBWDXRC"><b>Samsung Galaxy S10+</b></a> 128 GB with free AKG headphones $699.99 (reg $899.99)<br />
Unlocked <a href="https://www.amazon.com/Samsung-Factory-Unlocked-Warranty-Headphones/dp/B08225G1WW"><b>Samsung Galaxy Note 10+</b></a> 256 GB $899.99 (reg $1099.99)</p>
<hr />
<p><span style="font-size: 14pt;"><strong><a href="https://www.att.com/buy/prepaid-phones/browse/hasDeals">AT&amp;T Prepaid</a></strong></span> - <strong>Available in store and online  now until December 9, while supplies last</strong></p>
<p><a href="https://www.att.com/buy/prepaid-phones/alcatel-tetra-16gb-stealth-black-prepaid.html"><strong>Alcatel Tetra</strong></a> free with activation on $35 plan<br />
<a href="https://www.att.com/buy/prepaid-phones/lg-phoenix-4-16gb-titan-prepaid.html"><strong>LG Phoenix 4</strong></a> $9.99 with activation on $65 plan<br />
<a href="https://www.att.com/buy/prepaid-phones/samsung-galaxy-express-prime-3-16gb-black-prepaid.html"><strong>Samsung Galaxy Express 3</strong></a> $19.99 with activation on $50 plan<br />
<a href="https://www.att.com/buy/prepaid-phones/apple-iphone-6s-32gb-space-gray-prepaid.html"><strong>iPhone 6s</strong></a> 32 GB $99.99 with activation on $65 plan</p>
<hr />
<p><a style="font-weight: bold;" href="https://www.bhphotovideo.com/holiday-shopping/deals"><span style="font-size: 14pt;">B&amp;H</span></a><b> Cyber Monday sale</b> - Now through Dec 2. <strong>Items with links available online now.</strong></p>
<p>Unlocked <a href="https://www.bhphotovideo.com/c/product/1496570-REG/moto_pafg0014us_moto_e6_16gb_smartphone.html"><strong>Motorola Moto E6</strong></a> 16 GB $99.99 (reg $149.99)<br />
Unlocked <strong><a href="https://www.bhphotovideo.com/c/product/1500631-REG/moto_paae0011us_moto_g6_32gb_smartphone.html">Motorola Moto G6</a></strong> 32 GB $119.99 (was $249.99)<br />
Unlocked <a href="https://www.bhphotovideo.com/c/product/1455105-REG/moto_pae80008us_g7_play_32gb_smartphone.html"><strong>Motorola Moto G7 Play</strong></a> 32 GB $149.99 (reg $199.99)<br />
Unlocked <a href="https://www.bhphotovideo.com/c/product/1500630-REG/moto_pa9s0017us_moto_z3_play_32gb.html"><strong>Motorola Moto Z3 Play</strong></a> 32 GB $149.99 (was $349.99)<br />
Unlocked <a href="https://www.bhphotovideo.com/c/product/1500980-REG/lg_lmq720qm_ausabk_stylo_5_32gb_smartphone.html"><strong>LG Stylo 5</strong></a> 32 GB $169.99 (reg $299.99)<br />
Unlocked <strong><a href="https://www.bhphotovideo.com/c/product/1455104-REG/moto_paeb0006us_g7_power_32gb_smartphone.html">Motorola Moto G7 Power</a></strong> 32 GB $179.99 (reg $249.99)<br />
Unlocked <a href="https://www.bhphotovideo.com/c/product/1455102-REG/moto_pae00002us_g7_64gb_smartphone_unlocked.html"><strong>Motorola Moto G7 </strong></a>64 GB $199.99 (reg $299.99)<strong><br />
</strong>Unlocked<a href="https://www.bhphotovideo.com/c/product/1475547-REG/google_ga00655_us_pixel_3a_smartphone_unlocked.html"><strong> Pixel 3a</strong></a> 64 GB $299.99 (reg $399.99) <br />
Unlocked<strong><a href="https://www.bhphotovideo.com/c/product/1475550-REG/google_ga00664_us_pixel_3a_xl_smartphone.html"> Pixel 3a XL</a></strong> 64 GB $379.99 (reg $479.99)<br />
Unlocked <a href="https://www.bhphotovideo.com/c/product/1507476-REG/google_ga01188_us_pixel_4_64gb_smartphone.html"><strong>Pixel 4</strong></a> 64 GB $599.99 (reg $799.99)<br />
Unlocked <a href="https://www.bhphotovideo.com/c/product/1507482-REG/google_ga01181_us_pixel_4_xl_64gb.html"><strong>Pixel 4 XL</strong></a> 64 GB $699.99 (reg $899.99)<br />
Unlocked <a href="https://www.bhphotovideo.com/c/product/1456395-REG/samsung_sm_g970uzbaxaa_galaxy_s10e_sm_g970u_128gb.html"><b>Samsung Galaxy S10e</b></a> 128 GB $549.99 (reg $749.99)<br />
Unlocked <a href="https://www.bhphotovideo.com/c/product/1456403-REG/samsung_sm_g973uzkaxaa_galaxy_s10_sm_g973u_128gb.html"><b>Samsung Galaxy S10</b></a> 128 GB $699.99 (reg $899.99)<br />
Unlocked<a href="https://www.bhphotovideo.com/c/product/1491311-REG/samsung_sm_n970uzkaxaa_galaxy_note10_sm_n970u_256gb.html"><b> Samsung Galaxy Note 10</b></a> 256 GB $749.99 (reg $949.99)<br />
Unlocked <a href="https://www.bhphotovideo.com/c/product/1491315-REG/samsung_sm_n975uzsaxaa_galaxy_note10_sm_n975u_256gb.html"><b>Samsung Galaxy Note 10+</b></a> 256 GB $899.99 (reg $1099.99)</p>
<hr />
<p><strong><a style="text-decoration-line: none;" href="https://www.bestbuy.com/site/top-deals/cell-phone-deals/pcmcat1563302848653.c?id=pcmcat1563302848653"><span style="font-size: 16pt;"><span style="font-size: 14pt;">Best Buy</span></span></a></strong><strong> Cyber Monday sale</strong> – Based on past experience, Best Buy's Cyber Monday sale is expected to start Sunday Dec 1 and end Saturday December 7. <strong>Items with links available online now.</strong></p>
<p><strong>Prepaid phones:<br />
AT&amp;T Prepaid <a href="https://www.bestbuy.com/site/at-t-prepaid-motorola-moto-e5-play-with-16gb-memory-prepaid-cell-phone-black/6300370.p?skuId=6300370">Motorola Moto E5 Play </a></strong>$29.99 (reg $99.99)<strong><br />
</strong><strong>Tracfone <a href="https://www.bestbuy.com/site/tracfone-samsung-galaxy-j3-orbit-black/6288017.p?skuId=6288017">Samsung Galaxy J3 Orbit</a> S367VL</strong> 16 GB $34.99 (reg $79.99)<br />
<a href="https://www.bestbuy.com/site/clp-cell-phones/simple-mobile-activation-offer/pcmcat1573857290654.c?id=pcmcat1573857290654"><strong>$100 off select unlocked phones</strong></a> with purchase on a $1 Simple Mobile SIM and a $20 or more Simple Mobile airtime card.<br />
<a href="https://www.bestbuy.com/site/offer/356663/pcmcat1572539940482.c?id=pcmcat1572539940482"><strong>$50 off select unlocked phones</strong></a> with purchase on a $40 T-Mobile Prepaid SIM and airtime bundle<br />
<br />
<strong>Unlocked phones:</strong><br />
<a href="https://www.bestbuy.com/site/lg-k8-2018-with-16gb-memory-cell-phone-unlocked-moroccan-blue/6213513.p?skuId=6213513"><b>LG K8</b></a> 2018 16 GB 89.99 (reg $139.99)<br />
<a href="https://www.bestbuy.com/site/blu-vivo-xi-with-32gb-memory-cell-phone-unlocked-silver/6291857.p?skuId=6291857"><b>BLU Vivo XI</b></a> 32 GB $119.99 (reg $219.99)<br />
<a href="https://www.bestbuy.com/site/motorola-moto-g7-play-with-32gb-memory-cell-phone-unlocked-deep-indigo/6331397.p?skuId=6331397"><strong>Motorola Moto G7 Play</strong></a> 32 GB $149.99 (reg $199.99)<br />
<a href="https://www.bestbuy.com/site/motorola-moto-z3-play-with-32gb-memory-cell-phone-unlocked-deep-indigo/6348108.p"><strong>Motorola Moto Z3 Play</strong></a> 32 GB $149.99 (was $349.99)<br />
<a href="https://www.bestbuy.com/site/lg-stylo-5-aurora-black-unlocked/6363050.p?skuId=6363050"><strong>LG Stylo 5</strong></a> 32 GB $169.99 (reg $299.99)<br />
<strong><a href="https://www.bestbuy.com/site/motorola-moto-g7-power-with-32gb-memory-cell-phone-unlocked-marine-blue/6324289.p?skuId=6324289">Motorola Moto G7 Power</a></strong> 64 GB $179.99 (reg $249.99)<br />
<a href="https://www.bestbuy.com/site/motorola-moto-g7-with-64gb-memory-cell-phone-unlocked-ceramic-black/6324277.p?skuId=6324277"><strong>Motorola Moto G7</strong></a> 64 GB $199.99 (reg $299.99)<br />
<a href="https://www.bestbuy.com/site/blu-vivo-xi-with-64gb-memory-cell-phone-unlocked-silver/6288555.p?skuId=6288555"><b>BLU Vivo XI+</b></a> 64 GB $199.99 (reg $299)<br />
<b><a href="https://www.bestbuy.com/site/samsung-galaxy-a50-with-64gb-memory-cell-phone-unlocked-black/6361087.p?skuId=6361087">Samsung A50 </a></b>64 GB $274.99 (reg $349.99)<b><br />
</b><a href="https://www.bestbuy.com/site/google-pixel-3a-64gb-unlocked-just-black/6347785.p"><strong>Pixel 3a</strong></a> 64 GB $299.99 (reg $399.99)<strong><br />
<a href="https://www.bestbuy.com/site/google-pixel-3a-xl-64gb-unlocked-just-black/6347790.p">Pixel 3a XL</a></strong> 64 GB $379.99 (reg $479.99)<br />
<a href="https://www.bestbuy.com/site/learn-about-google-pixel-4/google-pixel-4-shop-by-carrier/pcmcat1570497903420.c?id=pcmcat1570497903420"><strong>Pixel 4</strong></a> 64 GB $599.99 (reg $799.99)<br />
<a href="https://www.bestbuy.com/site/learn-about-google-pixel-4/shop-by-carrier-google-pixel-4-xl/pcmcat1570498366095.c?id=pcmcat1570498366095"><strong>Pixel 4 XL</strong></a> 64 GB $699.99 (reg $899.99)<br />
<a href="https://www.bestbuy.com/site/samsung-galaxy-s10e-with-128gb-memory-cell-phone-unlocked-prism-prism-black/6323358.p?skuId=6323358"><b>Samsung Galaxy S10e</b></a> 128 GB $549.99 (reg $749.99)<br />
<a href="https://www.bestbuy.com/site/samsung-galaxy-s10-with-128gb-memory-cell-phone-unlocked-prism-prism-black/6323528.p?skuId=6323528"><b>Samsung Galaxy S10</b></a> 128 GB $699.99 (reg $899.99)<br />
<a href="https://www.bestbuy.com/site/samsung-galaxy-note10-with-256gb-memory-cell-phone-unlocked-aura-black/6359974.p?skuId=6359974"><b>Samsung Galaxy Note 10</b></a> 256 GB $749.99 (reg $949.99)<br />
<a href="https://www.bestbuy.com/site/samsung-galaxy-s10-with-128gb-memory-cell-phone-unlocked-prism-blue/6323867.p?skuId=6323867"><b>Samsung Galaxy S10+</b></a> 128 GB $799.99 (reg $999.99)<br />
<a href="https://www.bestbuy.com/site/samsung-galaxy-note10-with-256gb-memory-cell-phone-unlocked-aura-white/6359981.p?skuId=6359981"><b>Samsung Galaxy Note 10+</b></a> 256 GB $899.99 (reg $1099.99)</p>
<hr />
<p><strong><a href="https://www.cricketwireless.com/newsroom/news-release/holiday-device-promos.html"><span style="font-size: 14pt;">Cricket</span></a> Cyber Monday Sale </strong>is a continuation of the carrier's Black Friday sale, which runs through Jan 9, while supplies last. New items will be added on Cyber Monday . <strong>Items with links available in stores and online now.</strong></p>
<p><strong>$40/month <a href="https://www.cricketwireless.com/cell-phone-plans/40-unlimited-byod-plan">Promotional Plan</a></strong> with <strong>unlimited talk, messaging and "unlimited" high speed data</strong>. This plan does not include hotspot. Available for activation from Nov 22 to Jan 30 to customers who <strong>port a number</strong> and <strong>bring their own phone</strong> to Cricket.</p>
<p><b></b><b><strong><a href="https://www.cricketwireless.com/cell-phones/smartphones/Cricket-Icon.html">Cricket Icon</a></strong> free with port-in, $19.99 upgrade or new number<strong><br />
</strong><a href="https://www.cricketwireless.com/cell-phones/smartphones/alcatel-insight-gray.html"><strong>Alcatel INSIGHT</strong></a> free with port-in, $29.99 upgrade or new number<br />
<a href="https://www.cricketwireless.com/cell-phones/smartphones/lg-fortune2-titan-black.html"><strong>LG Fortune 2</strong></a> free with port-in, $39.99 upgrade or new number<br />
<a href="https://www.cricketwireless.com/cell-phones/smartphones/samsung-galaxy-j2-pure-black.html">Samsung J2 Pure</a></b> free with port-in and activation on $55 or $60 plan, 39.99 upgrade or new number<b><br />
<a href="https://www.cricketwireless.com/cell-phones/smartphones/lg-escape-plus.html">LG Escape Plus</a></b> free with port-in and activation on $55 or $60 plan, 49.99 upgrade or new number<b><br />
<a href="https://www.cricketwireless.com/cell-phones/smartphones/alcatel-onyx-suede">Alcatel Onyx</a></b> free with port-in and activation on $55 or $60 plan, 59.99 upgrade or new number<br />
<a href="https://www.cricketwireless.com/cell-phones/smartphones/nokia-3-1-C"><strong>Nokia 3.1 C</strong></a> free with port-in and activation on $55 or $60 plan, 69.99 upgrade or new number<br />
<a href="https://www.cricketwireless.com/cell-phones/smartphones/moto-e5-cruise-navy.html">Motorola e5 Cruise</a> free with port-in and activation on $55 or $60 plan, 39.99 upgrade or new number<br />
<strong><a href="https://www.cricketwireless.com/cell-phones/smartphones/apple-iphone-6s-32gb.html">Apple iPhone 6s</a></strong> 32 GB $49.99 with port-in and activation on $60 plan, $149.99 upgrade or new number<br />
<strong><a href="https://www.cricketwireless.com/cell-phones/smartphones/apple-iphone7-plus-32gb.html">Apple iPhone 7 Plus</a></strong> 32 GB $199.99 with port-in and activation on $60 plan, $299.99 upgrade or new number<br />
<strong><a href="https://www.cricketwireless.com/cell-phones/smartphones/apple-iphone-8">Apple iPhone 8</a></strong> 64 GB $349.99 with port-in and activation on $60 plan, $449.99 upgrade or new number<br />
<strong><a href="https://www.cricketwireless.com/cell-phones/smartphones/apple-iphone-8-128gb-space-gray.html">Apple iPhone 8</a></strong> 128 GB $399.99 with port-in and activation on $60 plan, $499.99 upgrade or new number<br />
<strong><a href="https://www.cricketwireless.com/cell-phones/smartphones/apple-iphone-xr-128gb-white.html">Apple iPhone XR</a></strong> 128 GB $549.99 with port-in and activation on $60 plan, $649.99 upgrade or new number<br />
<strong><a href="https://www.cricketwireless.com/cell-phones/smartphones/apple-iphone-11-64gb-green.html">Apple iPhone 11</a></strong> 64 GB $599.99 with port-in and activation on $60 plan, $699.99 upgrade or new number<br />
<strong><a href="https://www.cricketwireless.com/cell-phones/smartphones/apple-iphone-11-256gb-black.html">Apple iPhone 11</a></strong> 256 GB $749.99 with port-in and activation on $60 plan, $849.99 upgrade or new number</p>
<p><strong>Cyber Monday Sale</strong> starts Dec 2</p>
<p><a href="https://www.cricketwireless.com/cell-phones/smartphones/lg-stylo-5"><strong> LG Stylo 5</strong></a> $79.99 with port-in and activation. $179,99 upgrade or new number<strong><br />
<a href="https://www.cricketwireless.com/cell-phones/smartphones/moto-g7-supra">Motorola Moto G7 Supra</a></strong> $69.99 with port in and activation. $139,99 upgrade or new number<br />
<a href="https://www.cricketwireless.com/cell-phones/smartphones/Samsung-Galaxy-A10e.html"><strong>Samsung A10e</strong></a> $9.99 with port-in. $99,99 upgrade or new number<br />
<a href="https://www.cricketwireless.com/cell-phones/smartphones/samsung-galaxy-s10"><strong>Samsung Galaxy S10</strong></a> $399.99 with port in and activation on an unlimited plan. $700 (full price) for upgrade or new number</p>
<hr />
<p><strong><a href="https://www.ebay.com/sch/i.html?_nkw=prepaid+phone&amp;_sacat=0"><span style="font-size: 14pt;">eBay</span></a> - Available Now</strong></p>
<p>Red Pocket <strong><a href="https://www.ebay.com/itm/4-42-Mo-Red-Pocket-Prepaid-Wireless-Phone-Plan-Kit-100-Talk-100-Text-500MB/133058476404">SIM</a></strong> with 12 months of 100 minutes, 100 texts, 500 MB/month on AT&amp;T, Verizon, T-Mobile or Sprint $53 (4.42/month) (reg $59)<br />
Red Pocket <a href="https://www.ebay.com/itm/133058350672"><strong>SIM</strong></a> with 12 months of unlimited talk, text &amp; data, 1st 5 GB/month at high speed on AT&amp;T, Verizon or Sprint $195 (16.25/month) (reg $240)<br />
Red Pocket <strong><a href="https://www.ebay.com/itm/133058338802">SIM</a></strong> with 12 months of unlimited talk, text &amp; data, 1st 15 GB/month at high speed on AT&amp;T or Sprint $264 (22/month) (reg $399)<br />
Total Wireless <a href="https://www.ebay.com/itm/Total-Wireless-Samsung-Galaxy-A10e-4G-LTE-Prepaid-Smartphone-Locked-Black/283689750689"><strong>Samsung Galaxy A10e</strong></a> $49.99<br />
TracFone <a href="https://www.ebay.com/itm/Tracfone-LG-Rebel-4-4G-LTE-Prepaid-Cell-Phone-with-40-Airtime-Plan-Included/283585892236"><strong>LG Rebel 4</strong></a> with $40 bundled airtime $39.99<br />
TracFone <strong><a href="https://www.ebay.com/itm/Tracfone-Prepaid-Wireless-Smartphone-Plan-SIM-1200-Min-1200-Txt-3GB-Data/283493024108">SIM</a></strong> with 1200 Minutes, 1200 Texts, 3 GB Data on Verizon, AT&amp;T or T-Mobile good for one year $39.99 (reg $49.99)<br />
TracFone <a href="https://www.ebay.com/itm/Tracfone-Motorola-Moto-G6-4G-LTE-Prepaid-Phone-with-40-Airtime-Plan-Included/283549082723"><strong>Motorola Moto G6</strong></a> with $40 bundled airtime $79.99<br />
TracFone <strong><a href="https://www.ebay.com/itm/Tracfone-LG-Stylo-4-4G-LTE-Prepaid-Cell-Phone-with-40-Airtime-Plan-Included/283549223154">LG Stylo 4</a></strong> with $40 bundled airtime $79.99<br />
Tracfone <strong><a href="https://www.ebay.com/itm/Tracfone-Samsung-Galaxy-S7-4G-LTE-Prepaid-Phone-Refurbished/283685227427">Samsung Galaxy S7</a></strong> (refurbished) 32 GB (Verizon) $99.99 (was $599.99)<br />
Tracfone <strong><a href="https://www.ebay.com/itm/Tracfone-Samsung-Galaxy-S7-4G-LTE-Prepaid-Phone/283452915676">Samsung Galaxy S7</a></strong> (new) 32 GB (Verizon) $149.99 (was $599.99)<br />
Tracfone <strong><a href="https://www.ebay.com/itm/Tracfone-Samsung-Galaxy-S7-Smartphone-Gear-Sport-SmartWatch-1-Year-Service/283520714546">Samsung Galaxy S7</a></strong> (new) 32 GB with 1500 Minutes/Text/Data and 1 year of service and Samsung Gear Sport smartwatch (Verizon) $199.99<br />
Unlocked <a href="https://www.ebay.com/itm/283660734932"><strong>Samsung Galaxy Note 10+</strong></a> 512 GB $799.99 (reg $1,199.99) </p>
<hr />
<p><strong><span style="font-size: 14pt;"><a href="https://fi.google.com/about/phones/">Google Fi</a></span> Cyber Monday sale</strong> - <strong>now through Dec 2</strong></p>
<p>Unlocked <strong><a href="https://fi.google.com/about/phones/#moto-g7">Motorola Moto G7</a></strong> $99 with activation (reg $299)<br />
Unlocked <a href="https://fi.google.com/about/phones/#pixel-3a"><strong>Pixel 3a</strong></a> 64 GB $249 with activation (reg $399)<br />
Unlocked <a href="https://fi.google.com/about/phones/#pixel-3a"><strong>Pixel 3a XL </strong></a>64 GB $329.99 with activation (reg $479)</p>
<hr />
<p><a href="https://store.google.com/"><span style="font-size: 14pt;"><strong>Google Store</strong></span></a> <strong>Cyber Monday sale</strong> - <strong>now through Dec 2</strong></p>
<p>Unlocked <a href="https://store.google.com/product/pixel_3a"><strong>Pixel 3a</strong></a> 64 GB $299.99 (reg $399.99)<strong><br />
</strong>Unlocked <strong><a href="https://store.google.com/product/pixel_3a">Pixel 3a XL</a> </strong>64 GB $379.99 (reg $479.99)<strong><br />
</strong>Unlocked<strong> <a href="https://store.google.com/config/pixel_4">Pixel 4 </a></strong>64 GB $599.99 (reg $799.99)<br />
Unlocked<a href="https://store.google.com/config/pixel_4"><strong> Pixel 4 XL</strong></a> 64 GB $699.99 (reg $899.99)</p>
<hr />
<p><a href="https://www.hsn.com/shop/sale-cell-phones/ec0373-5544"><span style="font-size: 14pt;"><strong>HSN</strong></span></a> <strong>Ongoing sales now through Cyber Monday</strong>. New HSN customers get $20 off first order with code <strong>NEW20</strong></p>
<p>TracFone <a href="https://www.hsn.com/products/motorola-moto-e5-57-16gb-tracfone-w8mp-camera-and-1500-/8879320"><strong>Motorola Moto E5</strong></a> 16 GB with 1 year service and 1500 minutes, texts and MB $49.95<br />
TracFone <a href="https://www.hsn.com/products/lg-journey-545-hd-tracfone-with-case-and-1500-mintextda/9253399"><strong>LG Journey</strong></a> 16 GB with 1 year service and 1500 minutes, texts and MB $69.95</p>
<hr />
<p><strong><span style="font-size: 14pt;"><a href="https://www.t-mobile.com/news/metro-holiday-promo">Metro by T-Mobile</a></span> Cyber Monday </strong> is expected to start Sunday Dec 1 and end Saturday December 7.</p>
<p><strong>Live Now</strong> in stores only:<br />
<strong><a href="https://www.metrobyt-mobile.com/shop/phones/details/LG-K40/610214660732">LG K40</a></strong> free (reg $179.99) with port-in<br />
<a href="https://www.metrobyt-mobile.com/shop/phones/details/LG-Stylo-5/610214660770"><strong>LG Stylo 5</strong></a> 32 GB free (reg $239.99) with port-in<br />
<a href="https://www.metrobyt-mobile.com/shop/phones/details/moto-g-power-7th-gen/610214659842"><strong>Motorola Moto G7 Power </strong></a>free (reg $209.99) with port-in<br />
<strong><a href="https://www.metrobyt-mobile.com/shop/phones/details/Samsung-Galaxy-A10e/610214661203">Samsung Galaxy A10e </a></strong>free (reg $179.99) with port-in<br />
<a href="https://www.metrobyt-mobile.com/shop/phones/details/Samsung-Galaxy-A20/610214661197"><strong>Samsung Galaxy A20</strong></a> 32 GB free (reg $239.99) with port in<br />
<em>Limit 4 free phones per account/household. Requires validation of name, address and date of birth provided through independent database and presentation of matching identification and excludes numbers currently on T-Mobile network or active on Metro in past 90 days.<br />
</em><a href="https://www.metrobyt-mobile.com/bestdeal.html?icid=home|Nov19|bestdealP"><strong>Alcatel Joy Tab</strong></a> tablet free (reg $110). <em>Requires new tablet line of service and 2 phone lines on $60 base rate plan. Not valid in CT/RI/Miami-Dade.<br />
</em></p>
<hr />
<p><span style="font-size: 14pt;"><strong><a href="https://www.motorola.com/us/specials">Motorola</a></strong></span> <strong>Cyber Monday Sale</strong> available now to Dec 2. <strong>Items with links available online now.</strong></p>
<p>Unlocked <a href="https://www.motorola.com/us/products/moto-e-gen-6"><strong>Motorola Moto E6</strong></a> 16 GB $99.99 (reg $149.99)<br />
Unlocked <a href="https://www.motorola.com/us/products/moto-g-gen-6#buy"><strong>Moto G6</strong></a> 32 GB $119.99 or free with purchase of a full price $299.99 <strong>moto g7, </strong>$249.99 <strong>moto g6, </strong>$499.99 <strong>moto z4 unlocked</strong>, $299.99,<strong> moto z3</strong> , $349.99 <strong>moto one action</strong> or $449.99 <strong>motorola one zoom.</strong><br />
Unlocked <a href="https://www.motorola.com/us/products/moto-g-play-gen-7"><strong>Motorola Moto G7 Play</strong></a> 32 GB $149.99 (reg $199.99)<br />
Unlocked <strong><a href="https://www.motorola.com/us/products/moto-g-gen-7">Motorola Moto G7</a></strong> 64 GB $199.99 (reg $299.99)<br />
Unlocked <a href="https://www.motorola.com/us/products/moto-z-play-gen-3"><strong>Motorola Moto Z3 Play</strong></a> 32 GB with free folio or 2 free shells $149.99 (was $349.99)<br />
Unlocked<a href="https://www.motorola.com/us/products/motorola-one#buy"><strong> Motorola One</strong></a> 64 GB with free Moto G6 $249.99 (reg $399.99)<br />
Unlocked <a href="https://www.motorola.com/us/products/motorola-one-action"><strong>Motorola One Action</strong></a> 128 GB $249.99 (reg $349.99)<br />
Unlocked <a href="https://www.motorola.com/us/products/motorola-one-zoom"><strong>Motorola One Zoom</strong></a> 128 GB $349.99 (reg $449.99)<br />
Unlocked <a href="https://www.motorola.com/us/products/moto-z-gen-4-unlocked"><strong>Motorola Z4</strong></a> 128 GB $399.99 (reg $299.99)</p>
<hr />
<p><strong><a href="https://www.newegg.com/todays-deals?cm_sp=homepage_dailydeal-_--_-11302019"><span style="font-size: 14pt;">Newegg</span></a> Cyber Monday sale</strong> – TBA, <strong>online now</strong></p>
<p>Unlocked<a href="https://www.newegg.com/p/N82E16875705090"><strong> ZTE Axon 10 Pro</strong></a> 256 GB $499.99 (reg $599.99)</p>
<hr />
<p><strong><a href="https://www.oneplus.com/black-friday-2019"><span style="font-size: 14pt;">OnePlus</span></a> Cyber Monday sale</strong> now through Dec 2, while supplies last. <strong>Items with links available online now.</strong></p>
<p>Unlocked <a href="https://www.oneplus.com/oneplus-7pro?from=black-friday"><strong>OnePlus 7 Pro</strong></a> 256 GB $549 (reg $699.99)</p>
<hr />
<p><strong><a href="https://shop.simplemobile.com/shop/en/simplemobile/phones"><span style="font-size: 14pt;">Simple Mobile</span></a> - Available Now<br />
<br />
</strong><a href="https://shop.simplemobile.com/shop/en/simplemobile/phones/sm-iphone-6s-32gb">i<strong>Phone 6s</strong></a> 32 GB $99.99 (reg $159.99)<br />
<a href="https://shop.simplemobile.com/shop/en/simplemobile/phones/sm-iphone-6s-plus-32gb">i<strong>Phone 6s Plus</strong></a> 32 GB $149.99 (reg $199.99)</p>
<hr />
<p><strong><a href="https://shop.straighttalk.com/shop/en/straighttalk/phones"><span style="font-size: 14pt;">Straight Talk</span></a> - Available Now<br />
</strong></p>
<p><a href="https://shop.straighttalk.com/shop/en/straighttalk/phones/iphone-6s-32gb-gpapi6sc-p">i<strong>Phone 6s</strong></a> (Verizon) 32 GB $99.99 (reg $159.99)<br />
<a href="https://shop.straighttalk.com/shop/en/straighttalk/black-friday/iphone-6s-plus-32gb">i<strong>Phone 6s Plus</strong></a> (Verizon) 32 GB $149.99 (reg $199.99)<br />
<a href="https://shop.straighttalk.com/shop/en/straighttalk/phones/samsung-galaxy-s7-%28g930vl%29-stsag930vcp-p"><strong>Samsung Galaxy S7</strong></a> 32 GB $149.99 (was $499.99)</p>
<hr />
<p><span style="font-size: 14pt;"><a style="text-decoration-line: none;" href="https://www.target.com/c/cyber-monday/-/N-5q0f1"><strong>Target</strong></a></span> <b>Cyber Week sale: </b>Starts early Sunday, Dec. 1 and runs through Monday, Dec. 9, new deals daily. Best deals are expected Sunday and Monday. <strong>Items with links available online now.<br />
</strong></p>
<p><a href="https://www.target.com/p/at-38-t-prepaid-apple-iphone-7-32gb-with-50-airtime-included-black/-/A-54416918"><strong>AT&amp;T Prepaid Apple iPhone 7</strong></a> (32GB) with $50 bundled airtime $279.99 (reg $349.49) ends 12/2<br />
<a href="https://www.target.com/p/tracfone-prepaid-alcatel-myflip-4gb-flip-phone-gray/-/A-53661462"><strong>TracFone Alcatel MyFlip</strong></a> $9.99 (reg $19.99) <strong>Sold out online</strong><br />
<a href="https://www.target.com/p/verizon-prepaid-nokia-2v-8gb-black/-/A-54326120"><strong>Verizon Prepaid Nokia 2V</strong></a> 8 GB $34.99 (reg $69.99) ends 12/1</p>
<hr />
<p><strong><a href="https://shop.totalwireless.com/shop/en/totalwireless/phones"><span style="font-size: 14pt;">Total Wireless</span></a> - Available Now<br />
<br />
</strong><strong><a href="https://shop.totalwireless.com/shop/en/totalwireless/phones/tw-iphone-6s-32gb">iPhone 6s </a></strong>32Gb $99.99 (reg $159.99)<strong><br />
<a href="https://shop.totalwireless.com/shop/en/totalwireless/phones/tw-iphone-6s-plus-32gb">iPhone 6s Plus </a></strong>32 GB $149.99 (reg $199.99)</p>
<hr />
<p><strong><a href="https://shop.tracfone.com/shop/en/tracfonestore/phones/"><span style="font-size: 14pt;">TracFone</span></a> - Available Now </strong>use code <strong>BFCW30 </strong>for 30% off most phones.</p>
<p>Reconditioned i<a href="https://shop.tracfone.com/shop/en/tracfonestore/phones/tf-iphone-6s-space-grey-32gb-reconditioned"><strong>Phone 6s</strong></a> (Verizon) 32 GB $59.99 with $20 plan purchase (reg $119.99) <strong>Sold Out</strong><br />
<strong><a href="https://shop.tracfone.com/shop/en/tracfonestore/phones/tf-samsung-galaxy-s7">Samsung Galaxy S7</a></strong> (new) 32 GB (Verizon) $149.99 (was $599.99)</p>
<hr />
<p><strong><a href="https://www.walmart.com/cp/walmart-cyber-monday-deals-2019/546840"><span style="font-size: 14pt;">Walmart</span></a> Cyber Monday sale</strong>: Walmart's past Cyber Monday sales have been a continuation of its Black Friday sale with most of the same items plus some new ones. <strong>Items with links available online now. Most deals end Dec 2.</strong></p>
<p><strong>Straight Talk <a href="https://www.walmart.com/ip/Straight-Talk-Samsung-Galaxy-A10e-Smartphone/286888400">Samsung Galaxy A10e</a></strong> $49 (reg $139)<br />
<strong>Straight Talk <a href="https://www.walmart.com/ip/seort/266155408">LG Stylo 5</a></strong> $99 (reg $199)<br />
<strong>Straight Talk <a href="https://www.walmart.com/ip/Straight-Talk-Apple-iPhone-6s-Prepaid-Smartphone-with-32GB-Space-Gray/863424218">iPhone 6s</a></strong> $99 (reg $149)<br />
<strong>Straight Talk <a href="https://www.walmart.com/ip/Straight-Talk-Prepaid-Apple-iPhone-6s-Plus-32GB-Space-Gray/947596782">iPhone 6s Plus</a></strong> $149 (reg $199)<br />
<strong>Straight Talk <a href="https://www.walmart.com/ip/seort/910201860">Samsung Galaxy S9</a></strong> $399 (reg $599)<br />
<strong>Total Wireless <a href="https://www.walmart.com/ip/Total-Wireless-Apple-iPhone-6s-32GB-Prepaid-Smartphone-Space-Gray/767320621">iPhone 6s</a></strong> $99 (reg $149)<br />
<strong>Total Wireless <a href="https://www.walmart.com/ip/Total-Wireless-Apple-iPhone-6s-Plus-32GB-Prepaid-Smartphone-Space-Gray/443728559">iPhone 6s Plus</a></strong> $149 (reg $199) <br />
<strong>TracFone </strong><a href="https://www.walmart.com/ip/TracFone-Alcatel-MyFlip-Prepaid-Phone/564300365"><strong>MyFlip</strong></a> flip phone $11.08 (reg $19.99)<br />
<strong>Unlocked</strong> <a href="https://www.walmart.com/ip/Google-Pixel-XL-3a-White-Factory-Unlocked/816345755"><strong>Pixel 3a XL </strong></a>64 GB $379.99 (reg $479.99)<br />
<strong>Walmart Family Mobile <a href="https://www.walmart.com/ip/Walmart-Family-Mobile-LG-Journey-Smartphone/879071964">LG Journey</a></strong> $39.88 (reg $79)</p>
<hr />
<p><b>Sources:</b> <a style="text-decoration-line: none;" href="https://www.bfads.net/">BFAds.net</a>, <a href="https://turkforums.jcink.net/index.php?showtopic=220&amp;hl=black+friday">Turk Forums</a>, <a href="https://www.howardforums.com/showthread.php/1916317">Howard Forums</a>, <a href="https://bestmvno.com/cricket-wireless/cricket-wireless-holiday-deals-unlimited-data-plan-free-phones/">BestMVNO</a>, <a href="https://slickdeals.net/newsearch.php?q=prepaid+phone&amp;firstonly=1">SlickDeals</a></p>