<h2>2020 Black Friday Prepaid and Unlocked Phone Deals</h2>
<p>This year Black Friday, the day after Thanksgiving. falls on November 27.</p>
<p>Black Friday pre-sales start several weeks before Black Friday. The best deals often go live on Thanksgiving Day. I expect the ongoing COVID-19 pandemic to have a big impact on Black Friday this year, with more online sales and longer sale windows.</p>
<p>I also don't expect to see as deep discounts this year due to a combination of increased tariffs and the departure of Boost and Verizon Prepaid from Target, AT&amp;T Prepaid, Boost and Cricket from Best Buy and Boost from Dollar General.</p>
<p>This page lists of all the Black Friday prepaid and unlocked phone deals I’ve discovered to date. It will be updated when new deals surface.</p>
<p>Follow me, <a style="text-decoration-line: none;" href="https://twitter.com/yeswap">@yeswap on Twitter</a> for the latest updates.</p>
<p><strong>Items with links are currently available online.</strong></p>
<p><span style="font-size: 14pt;"><strong>Amazon</strong></span></p>
<p>I expect Amazon to do what it always does; constantly raising and lowering prices with little or no advanced warning. Amazon tends to silently meet or beat competitors best deals. Here are Amazon's best current prepaid and unlocked phone deals:</p>
<p><strong>Unlocked phones</strong></p>
<p><strong>Motorola <a href="https://www.amazon.com/Moto-G7-Power-Unlocked-Warranty/dp/B07N9KQDVG">Moto G7 Power </a></strong>32 GB 131.99 (was $249.00)<strong><br />
Motorola</strong> <a href="https://www.amazon.com/Moto-Unlocked-Motorola-Camera-White/dp/B086H4C8CX"><strong>Moto G Fast</strong></a> 32 GB 149.99 (reg $299.00)<br />
<strong>Motorola</strong> <a href="https://www.amazon.com/Power-Battery1-Unlocked-Motorola-Camera/dp/B084D89DBF"><strong>Moto G Power</strong></a> 64 GB 179.99 (reg $249.00)<br />
<strong>Motorola</strong> <a href="https://www.amazon.com/Stylus-Unlocked-Motorola-Camera-Indigo/dp/B084CVPLLC"><strong>Moto G Stylus</strong> </a>128 GB 199.99 (reg $299.00)<br />
<b>Samsung <a href="https://www.amazon.com/Samsung-Factory-Unlocked-Storage-Compatible/dp/B086FKHTLZ">Galaxy A51</a></b> 128GB GB $324.99 (reg $399.99)<br />
<strong>Motorola</strong><a href="https://www.amazon.com/Motorola-Unlocked-256GB-Camera-Solar/dp/B08B9SGGRS"><strong>Moto Edge 5G</strong></a> 256 GB 399.99 (reg $699.99)<br />
<b>Samsung <a href="https://www.amazon.com/Samsung-Unlocked-Storage-Lasting-Battery/dp/B08BX67ZNV">Galaxy A71 5G</a></b> 128GB GB $494.79 (reg $599.99)<br />
<b>Samsung <a href="https://www.amazon.com/Samsung-Unlocked-Fingerprint-Recognition-Long-Lasting/dp/B082XY23D5">Galaxy S20 5G</a></b> 128GB GB $799.99 (reg $999.99)<b><strong><br />
</strong></b></p>
<p><strong><a style="text-decoration-line: none;" href="https://www.bestbuy.com/site/black-friday/cell-phone-ad/pcmcat1568908277830.c"><span style="font-size: 14pt;">Best Buy</span></a></strong> <a href="https://www.dealsplus.com/blackfriday/adscan/best-buy">Ad scan</a> (DealsPlus.com) phones are on pp 14 - 17.</p>
<p><b>Black Friday Pre-Sale</b> On Now with many items (the ones with links below) at "guaranteed" lowest Black Friday prices. Pre-sale ends Sunday Nov. 1 at 11:59 p.m. CT.</p>
<p><strong>Black Friday sale</strong> Starts Sunday November 22 with additional online only items starting at 12:01am PT Thursday Thanksgiving. Stores closed Thanksgiving, reopen Friday.</p>
<p><strong>Locked prepaid phones:</strong></p>
<p><strong>Total Wireless iPhone</strong> <strong>7</strong> 32 GB $99.99 (reg $199.99)<br />
<strong>Tracfone LG Premier Pro Plus</strong> 32 GB $49.99 (reg $99.99)<br />
<strong>Verizon Prepaid Samsung Galaxy</strong> <strong>A01 </strong>16 GB $64.99 (reg $99.99)<strong><br />
Verizon Prepaid Moto E Fast </strong>32 GB 79.99 (reg $129.00)</p>
<p><strong>Unlocked phones:</strong></p>
<p><strong>Motorola</strong> <a href="https://www.bestbuy.com/site/motorola-moto-g-fast-with-32gb-memory-cell-phone-unlocked-pearl-white/6411990.p?skuId=6411990"><strong>Moto G Fast</strong></a> 32 GB 149.99 (reg $299.00)<br />
<strong>Motorola</strong> <a href="https://www.bestbuy.com/site/motorola-moto-g-power-cell-phone-with-64gb-memory-unlocked-smoke-black/6398516.p?skuId=6398516"><strong>Moto G Power</strong></a> 64 GB 179.99 (reg $249.00)<br />
<strong>Motorola</strong> <a href="https://www.bestbuy.com/site/motorola-moto-g-stylus-cell-phone-with-128gb-memory-unlocked-mystic-indigo/6398515.p?skuId=6398515"><strong>Moto G Stylus</strong></a> 128 GB 199.99 (reg $299.00)<b><strong><br />
</strong></b><b>Samsung Galaxy A21</b> 32GB GB $199.99 (reg $249.99)<br />
<b>Samsung <a href="https://www.bestbuy.com/site/samsung-galaxy-a51-with-128gb-memory-cell-phone-unlocked-prism-crush-black/6404315.p?skuId=6404315">Galaxy A51</a></b> 128GB GB $324.99 (reg $399.99)<br />
<strong>Motorola </strong><a href="https://www.bestbuy.com/site/motorola-moto-edge-5g-256gb-unlocked-solar-black/6417451.p?skuId=6417451"><strong>Moto Edge 5G</strong></a> 256 GB 399.99 (reg $699.99)<br />
<b>Samsung <a href="https://www.bestbuy.com/site/samsung-galaxy-a71-5g-128gb-unlocked-prism-cube-black/6420105.p?skuId=6420105">Galaxy A71 5G</a></b> 128GB GB $499.99 (reg $599.99)<br />
<b>Samsung Galaxy S20 FE 5G</b> 128GB GB $549.99 (reg $599.99)<br />
<b>Google Pixel 5 5G</b> 128GB GB $649.99 (reg $699.99)<br />
<b>Samsung Galaxy Note20 5G</b> 128 GB $749.99 (reg $999.99)<br />
<b>Samsung <a href="https://www.bestbuy.com/site/samsung-galaxy-s20-5g-enabled-128gb-unlocked-cosmic-gray/6395751.p?skuId=6395751">Galaxy S20 5G</a></b> 128GB GB $799.99 (reg $999.99)<br />
<b>Samsung Galaxy S20+ 5G</b> 128GB GB $949.99 (reg $1199.99)<br />
<strong>Motorola </strong><a href="https://www.bestbuy.com/site/motorola-moto-razr-5g-256gb-unlocked-polished-graphite/6425587.p?skuId=6425587"><strong>Razr 5G</strong></a> 256 GB 999.99 (reg $1399.99)<br />
<b>Samsung Galaxy Z Flip</b> 256GB GB $1099.99 (reg $1299.99)<br />
<b>Samsung <a href="https://www.bestbuy.com/site/samsung-galaxy-note20-ultra-5g-128gb-unlocked-mystic-bronze/6420838.p?skuId=6420838">Galaxy Note20 Ultra 5G</a></b> 128 GB $1099.99 (reg $1299.99)<br />
<b>Samsung Galaxy S20 Ultra 5G</b> 128GB GB $1149.99 (reg $1399.99)<br />
<b><strong>Microsoft <a href="https://www.bestbuy.com/site/microsoft-surface-duo-128gb-unlocked-glacier/6419335.p?skuId=6419335">Surface Duo</a> </strong></b>128 GB 1199.99 (reg $1399.99)<b><br />
Samsung Galaxy Z Flip 5G</b> 256GB GB $1299.99 (reg $1499.99)<br />
<br />
</p>
<hr />
<p><b></b><span style="font-size: 14pt;"><a style="text-decoration-line: none;" href="https://weeklyad.target.com/promotions?code=Target-00181104&amp;page=D0"><strong>Target</strong></a></span></p>
<p><b>Black Friday sale: </b>Nov. 22- 28. Weeky pre-Black Friday sales Nov 1-7, 8-15 and 15-21.<br />
<br />
In the past, Target has offered all their cell phone door busters online.<br />
All online orders get free 2 day shipping.</p>
<hr />
<p><a href="https://www.samsclub.com/b/instant-savings-book/6930116?mid=hp_pov_201028_isb_11nov&amp;xid=hpg_pov_1_1"><span style="font-size: 14pt;"><strong>Sams Club</strong></span></a></p>
<p><strong>Presale on now</strong></p>
<p><strong>Simple Mobile <a href="https://www.samsclub.com/p/samsung-a50-prepaid-phone-card/prod24522606?xid=plp_product_12">Samsung A50</a></strong> $189.98 (reg $244.98) <br />
<strong>Total Wireless <a href="https://www.samsclub.com/p/samsung-a50-prepaid-phone-card/prod24522604?xid=plp_product_7">Samsung A50</a></strong> $189.98 (reg $244.98) ends Nov 29</p>
<hr />
<p><a href="https://www.walmart.com/cp/walmart-black-friday-2020/1076614"><span style="font-size: 14pt;"><strong>Walmart </strong></span></a></p>
<p>This year Walmart is doing two online pre-sales as well as the main Black Friday event.</p>
<ul>
	<li>Pre-sale 1 starts Nov 4 at 7PM ET with new deals starting Nov 7 at 12AM ET.</li>
	<li>Pre-sale 2 starts Nov 11 at 7PM ET with new deals starting Nov 14 at 12AM ET online and 5AM local time in stores.</li>
	<li>The Black Friday sale starts Nov 25 at 7PM ET with new deals starting Nov 27 at 12AM ET online and 5AM local time in stores.</li>
</ul>
<p><b>AT&amp;T Prepaid Samsung Galaxy A11 </b>$49 (reg $149) In store activation on Nov14 required<br />
<b>Total Wireless iPhone SE </b>$199 (reg $349) starts Nov 14<br />
<strong>Total Wireless iPhone XR </strong>$299 (reg $399) starts Nov 14<br />
<b>Straight Talk Moto E</b> $39.88 (reg $99) starts Nov 14<br />
<strong>Straight Talk Samsung Galaxy A21</strong> $99 (reg $249) starts Nov 14<br />
<strong>Straight Talk Samsung Galaxy A51</strong> $199 (reg $399) starts Nov 14<br />
<strong>Straight Talk iPhone SE </strong>$199 (reg $349) starts Nov 14<br />
<strong>Straight Talk iPhone XR </strong>$299 (reg $399) starts Nov 14<br />
<strong>Straight Talk Samsung Galaxy S10e</strong> $399 (reg $599) starts Nov 14<br />
<b>Verizon Prepaid Samsung Galaxy A11 </b>$49 (reg $149) In store activation on Nov 14 required</p>
<hr />
<p><b>Sources:</b> <a href="https://slickdeals.net/blackfriday/">Slickdeals</a>, <a href="https://turkforums.jcink.net/index.php?showtopic=313&amp;st=0&amp;#entry5753">Turk Forums</a></p>